### ISSUE TITLE
Offboard mode

### ISSUE THREAD

**Issue by lucasantoro** [20chix/Autonomus_Indoor_Drone#25]
Good evening,
I'm developing a similar project, but on Ubuntu 18.04 and Ros melodic with px4.
Your project can run on this environment? 
Is it possible to set offboard navigation and use a list of points? 
I don't understand if uwb system is simulated or Simply you get data from real hardware.

In any case, maybe I can help you with the hardware part and improve this repository with my work.
Thank you very much for your time and consideration

**Comment by 20chix** [comment]
Hi,

This project can also work in Ubuntu 18.04 and ros melodic but with ardupilot
Not to sure about offboard navigation.
UWB can be simulated by adding xyz coordinates in an xml file and they 'll be imported into gazebo.
It can also get the real position from UWB into Gazebo and you can choose from RQT.

That would be nice, is been a while since I worked on this project.

**Comment by lucasantoro** [comment]
Hi dear,
so do you think that convert it to PX4 firmware is difficult?

**Comment by 20chix** [comment]
I don't think it should be difficult as px4 and ardupilot are really similar, however I have to point out that px4 firmware is quite challenging to understand depends, so might be worth reading the docs before diving into the code.

Feel free to upload PRS I'll be happy to review them and merge them .
